issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:xchanming/cicada:ref:refs/tags/v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+
claim_pattern:
  job_workflow_ref: xchanming/cicada/.github/workflows/05-publish-release.yml@refs/tags/v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+

permissions:
  actions: write
